name: flavorbanner
description: Flavor Banner.
version: 1.0.1
author: Alberto Díaz Adorna
homepage: https://github.com/p02diada/flutter-flavor-banner

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_info: ^2.0.2
  package_info_plus: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

